/**
 * Build `lib/client.js` from `src/client/*.js`.
 *
 * Why a build step at all: a DSH browser plugin bundle must be a classic script
 * that calls `window.__ModuleLoader__.load({ id, factory })`, and every module
 * body has to live inside that factory closure. Writing ~2.5k lines in one file
 * is unmaintainable, so the sources live in `src/client/` and this script wraps
 * them in a minimal CommonJS-style registry:
 *
 *   - inside a source module, `m('model')` loads a sibling module by id
 *   - `require('react')` still means the platform's seed-table require
 *   - module ids are the file basenames, loaded in the ORDER below
 *
 * The generated file is committed (the Host serves `lib/client.js` as-is and
 * requires it to exist before launch).
 *
 * Usage: node tools/build-client.mjs
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = path.dirname(fileURLToPath(import.meta.url))
const ROOT = path.resolve(HERE, '..')
const SRC = path.join(ROOT, 'src', 'client')
const OUT = path.join(ROOT, 'lib', 'client.js')
const PKG = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf8'))

/** Load order matters: `apply` last, everything it needs before it. */
const ORDER = [
  'strings',
  'model',
  'store',
  'ai',
  'ui-kit',
  'ui-canvas',
  'ui-inspector',
  'ui-app',
  'apply',
]

const INDENT = '\t\t'

/** Indent a source module so the generated file stays readable. */
function indent(text, pad) {
  return text
    .replace(/\s+$/, '')
    .split('\n')
    .map((line) => (line.length > 0 ? pad + line : line))
    .join('\n')
}

const missing = ORDER.filter((id) => !fs.existsSync(path.join(SRC, id + '.js')))
if (missing.length > 0) {
  console.error('missing source modules: ' + missing.join(', '))
  process.exit(1)
}

const modules = ORDER.map((id) => {
  const source = fs.readFileSync(path.join(SRC, id + '.js'), 'utf8')
  return [
    `${INDENT}/* --- src/client/${id}.js --- */`,
    `${INDENT}__def(${JSON.stringify(id)}, function (module, exports, require, m) {`,
    indent(source, INDENT + '\t'),
    `${INDENT}});`,
    '',
  ].join('\n')
}).join('\n')

const bundle = `/* Generated by tools/build-client.mjs — do not edit; edit src/client/*.js and rebuild. */
window.__ModuleLoader__.load({
\tid: ${JSON.stringify(PKG.name)},
\tfactory: (require) => {
\t\tvar module = { exports: {} };
\t\tvar exports = module.exports;
\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });
\t\tvar __mods = Object.create(null);
\t\tvar __cache = Object.create(null);
\t\tfunction __def(id, fn) { __mods[id] = fn }
\t\tfunction __m(id) {
\t\t\tif (__cache[id] !== void 0) return __cache[id].exports;
\t\t\tvar fn = __mods[id];
\t\t\tif (fn === void 0) throw new Error("[dsh-ui-flow-mapper] unknown internal module: " + id);
\t\t\tvar mod = { exports: {} };
\t\t\t__cache[id] = mod;
\t\t\tfn(mod, mod.exports, require, __m);
\t\t\treturn mod.exports;
\t\t}
${modules}
\t\tvar api = __m("apply");
\t\texports.apply = api.apply;
\t\texports.inject = api.inject;
\t\texports.__name = ${JSON.stringify(PKG.name)};
\t\t/* Debug hatch: lets tools/test-client.mjs reach internal modules. */
\t\texports.__internal = __m;
\t\treturn module.exports;
\t}
});
`

fs.mkdirSync(path.dirname(OUT), { recursive: true })
fs.writeFileSync(OUT, bundle)
const lines = bundle.split('\n').length
console.log(`built ${path.relative(ROOT, OUT)} — ${bundle.length} bytes, ${lines} lines, ${ORDER.length} modules`)
